### PR TITLE
reducing cache time, caching only along tweet rather than token dimensio...

### PR DESCRIPTION
**Pull request by talos**
...ns

### CODE REVIEW

**Comment by eriktaubeneck** [comment]
@talos I added `timeout` as a kwarg when initializing the class, and also added some defaults. I'm not sure what the other defaults are, but if we want to test them someday, we could add more.

Anything else worth adding before I increment the version and release it on PyPi?

**Comment by talos** [comment]
@eriktaubeneck Looks good.  Should there be some check to ensure that the kwarg `timeout` doesn't exceed `twitter_timeout`?

**Comment by eriktaubeneck** [comment]
Yep, added an exception that will get raised, and added a test for it. (I'm using [Flask-Testing](http://pythonhosted.org/Flask-Testing/) and I really hate the way I have to test for raising an exception, but I'm too lazy at this point to rewrite the tests completly...)

**Comment by talos** [comment]
Made one small comment, but looks good to go!

**Pull request merged**
